<?php
// Template Name: step7
get_header();
?>
<div class="container">
    <div class="row ">
        <div class="col-sm-12 col-md-10 col-lg-8">
            <form data-action="step-Eight" id="myForm" class=" m-3">
                <h1>Entity Classification</h1>
                <h5 class=" text-dark alert alert-primary show shadow">
                    To qualify for S Corporation status, the corporation must be a domestic corporation; have only one class of stock; and have not more than 35 stockholders, who must be individuals, estates, or certain trusts
                </h5>
                <h3>Most new corporations files in the State of Flabiz elect S Corporation status.</h3>
                <p>
                    An S Corporation is a corporation which has elected a special tax status. This tax treatment permits the income of the corporation to be "passed through" to the shareholders. Thus, shareholders report the income or loss which is generated by an S Corporation on their individual tax returns. In order to be considered an S Corporation, the stockholders of a properly filed corporation must elect such status within 75 days of formation for the current tax year, or at any time during the preceding tax year. This election is made by filing Form 2553 with the Internal Revenue Service (IRS). We offer this as an option for only $39.
                </p>
                <h3>Do you wish to file the S Corporation election form?</h3>


                <div class="ml-md-auto col-sm-12 d-flex justify-content-between align-items-center mt-5">
                    <div class="box-checkbox border border-2 border-success rounded  m-2 p-2 ">
                        <input class="custom-control-input m-2 form-check-input " type="checkbox" id="checkbox11"  name="checkbox11">
                        <label for="checkbox11">
                            <span>
                                <h4>Yes, file the S Corporation election form</h4>
                            </span>
                        </label>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-lg-6 col-md-6 col-sm-12 mt-1">
                        <a id="my-link" href="step-six" class="btn btn-success text-white shadow ">Previous</a>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 mt-1">
                            <input type="submit" value="Next" class="btn border-success text-success shadow "> 
                        </div>
                </div>
            </form>
        </div>
        <div class="col">
            <?php get_sidebar(); ?>
        </div>
    </div>
</div>

<?php
get_footer();

?>