<?php
// Template Name: step9
get_header();
?>
<div class="container">
    <div class="row d-flex">
        <div class="col-sm-12 col-md-10 col-lg-8">
            <form id="myForm" data-action="step-ten" class=" m-3">
            <h2>Last Steps</h2>
                <p>
                    You're almost done! Upon completion of the registration, it will be posted with the Division of Corporations in 1-2 business days. You will receive an email confirmation of your filing (at).
                    <span class="info-data me-3" id="email2"></span>
                </p>
                <p>
                    An S Corporation is a corporation which has elected a special tax status. This tax treatment permits the income of the corporation to be "passed through" to the shareholders. Thus, shareholders report the income or loss which is generated by an S Corporation on their individual tax returns. In order to be considered an S Corporation, the stockholders of a properly filed corporation must elect such status within 75 days of formation for the current tax year, or at any time during the preceding tax year. This election is made by filing Form 2553 with the Internal Revenue Service (IRS). We offer this as an option for only $39.
                </p>
                <h3>Notice of Annual Report</h3>
                <p>
                    This corporation must file an Annual Report with the Division of Corporations between January 1st and May 1st of every year to maintain "active" status. The corporation's first annual report will be due between January 1st and May 1st of the calendar year following the year the corporation is formed and must be filed online. The fee to file a Corporation Annual Report is $150 And the fee to file an LLC Annual Report is $138. A $400 late fee is applied if the report is filed after May 1st. Reminder notices to file the Annual Report will be sent to the e-mail address you provide in these articles. File early to avoid the late fee.
                </p>
                <p>
                    The final step is to authorize Flabiz Incorporation Service to file these documents with the Division of Corporations on your behalf. Because our service is entirely online, this is done by providing your "electronic signature," meaning simply that you must provide your contact information below, accept the user agreement, and type your name into the electronic signature box at the bottom.
                </p>
                <!-- 2 column grid layout with text inputs for the first and last names -->
                <div class="row mb-4">
                    <div class="col">
                        <div class="form-outline">
                            <label class="form-label" for="NameOnCard">Name on card</label>
                            <input type="text" id="NameOnCard" data-error="Name on card is required"
                                class="form-control" data-required="true" />
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-outline">
                            <label class="form-label" for="CardNumber">Credit card number</label>
                            <input type="number" id="CardNumber" data-error="Card number is required"
                                class="form-control card" data-required="true" />
                        </div>
                    </div>
                </div>
                <!-- Text input -->
                <p>Your Card Verification Number (CVN/CVV) protects you from fraudulent purchases. Please provide this
                    number to increase the security of your purchase.</p>
                <div class="form-outline">
                    <label class="form-label" for="CVV">CVN/CVV</label>
                    <input type="text" id="CVV" data-error="CVN/CVV is required" class="form-control"
                        data-required="true" />
                </div>
                <div class="form-outline">
                    <label class="form-label" for="Expiration">Expiration</label>
                    <input type="date" id="Expiration" data-error="Expiration is required" class="form-control"
                        data-required="true" />
                </div>
                <h5 class="mb-4">Payment</h5>
                <select name="paymentCard" id="paymentCard" data-error="card type is required" class="form-control"
                    data-required="true" data-error="Card is required">
                    <option value="">Select card</option>
                    <option value="MasterCard">Master card</option>
                    <option value="visaCard">Visa card</option>
                    <option value="AmericanExpress">American Express</option>
                    <option value="Discover">Discover</option>
                </select>
                



                <hr class="my-4" />
                <div class="row mt-5">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <a href="step-six" class="btn btn-success text-white">Previous</a>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 d-flex flex-column">
                        <input class="btn btn-success text-white" type="submit" value="Next">
                    </div>
                </div>
            </form>
        </div>
        <!-- Error Modal -->
        <div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-black fw-bold" id="exampleModalLabel">Oops, please fix the following
                            issues:</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="modal-error">

                    </div>
                    <div class="modal-footer">
                        <button type="button" data-bs-dismiss="modal" class="btn btn-primary">OK</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <?php get_sidebar(); ?>
        </div>
    </div>
</div>
</div>
<?php
get_footer();

?>